# Generated by Django 6.1.1 on 2026-09-22 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0004_job_job_active_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='app_job_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', '-applied_at'], name='app_candidate_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-updated_at'], name='app_status_updated_idx'),
        ),
    ]
